POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "name",
    "dateOfBirth": "1991-10-10",
    "ssn": "qwerty",
    "gender": "no",
    "occupation": "no" 
}

###

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "type": "OccupationalHealthcare",
    "description": "test",
    "date": "2022-10-06",
    "specialist": "test",
    "employerName": "test"
}

###

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "type": "Hospital",
    "description": "test",
    "date": "2022-10-06",
    "specialist": "test",
    "discharge": {
        "date": "2022-12-06",
        "criteria": "test"
    }
}

###

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "type": "HealthCheck",
    "description": "test",
    "date": "2022-10-06",
    "specialist": "test",
    "healthCheckRating": 0,
    "diagnosisCodes": [["S62.5"]]
}